# Exploring Datasets

Importing libraries required

In [26]:
import numpy as np
import pandas as pd

import geoviews as gv
import geoviews.feature as gf
import xarray as xr
import rasterio as rio

import os
import hvplot.xarray
import hvplot.pandas
import geopandas
import warnings
warnings.filterwarnings('ignore')

## Reading Objects Rasterios

In [29]:
file1 = '../../../data/raw/merged.tif'

#Rasterios merged
file_path = '../../../data/raw/all_tif_merged.tif'

In [30]:
ds1 =  xr.open_rasterio(file1)
ds1

<xarray.DataArray (band: 2, y: 1250, x: 3600)>
[9000000 values with dtype=float32]
Coordinates:
  * band     (band) int64 1 2
  * y        (y) float64 69.95 69.85 69.75 69.65 ... -54.65 -54.75 -54.85 -54.95
  * x        (x) float64 -179.9 -179.8 -179.8 -179.7 ... 179.7 179.8 179.9 180.0
Attributes:
    transform:      (0.1, 0.0, -180.0, 0.0, -0.1, 70.0)
    crs:            +init=epsg:4326
    res:            (0.1, 0.1)
    is_tiled:       0
    nodatavals:     (-3.4028234663852886e+38, -3.4028234663852886e+38)
    scales:         (1.0, 1.0)
    offsets:        (0.0, 0.0)
    AREA_OR_POINT:  Area

## Exploring values in XArray.Dataset

In [35]:
ds1.x[0:10]

<xarray.DataArray 'x' (x: 10)>
array([-179.95, -179.85, -179.75, -179.65, -179.55, -179.45, -179.35, -179.25,
       -179.15, -179.05])
Coordinates:
  * x        (x) float64 -179.9 -179.8 -179.8 -179.7 ... -179.2 -179.2 -179.1

In [36]:
ds1.y[0:10]

<xarray.DataArray 'y' (y: 10)>
array([69.95, 69.85, 69.75, 69.65, 69.55, 69.45, 69.35, 69.25, 69.15, 69.05])
Coordinates:
  * y        (y) float64 69.95 69.85 69.75 69.65 ... 69.35 69.25 69.15 69.05

In [39]:
ds1.values[0][0][0:10]

array([-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
       -3.4028235e+38, -3.4028235e+38], dtype=float32)

In [47]:
ds1.values[ds1.values>0][0:10]

array([2.5, 2.4, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.2, 2.3], dtype=float32)

In [48]:
ds1.attrs

{'transform': (0.1, 0.0, -180.0, 0.0, -0.1, 70.0),
 'crs': '+init=epsg:4326',
 'res': (0.1, 0.1),
 'is_tiled': 0,
 'nodatavals': (-3.4028234663852886e+38, -3.4028234663852886e+38),
 'scales': (1.0, 1.0),
 'offsets': (0.0, 0.0),
 'AREA_OR_POINT': 'Area'}

## Reading Rasterio Merged with all years

In [31]:
ds = xr.open_rasterio(file_path)

## Cleaning Rasterio

In [32]:
# Band as years
da = xr.DataArray(np.arange(1999, 2020), dims=['band'])
sublist = np.arange(2017, 2019)
mask = np.isin(da, sublist, invert=True)
da = da[mask]
ds['band'] = da

# make zero negative values 
ds.values[ds.values<0] = -100

## Brief Visualization of Rasterio Data in Map

In [33]:
ds.sel().hvplot.image(cmap='terrain', rasterize=True, data_aspect=2,frame_width=600)

:DynamicMap   [band]
   :Image   [x,y]   (value)